name: GitHub Actions Demo

on: [push]

jobs:
  myAction:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package

      - name: Depcheck
        run: |
            sh owasp-dependency-check.sh
