
on: [push]

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build project with Maven
        run: mvn clean install
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
          args: >
            --failOnCVSS 7
            --enableRetired
             steps:    
             - name: Deploy to tomcat
               uses: actions/checkout@v2
               run: scp /home/runner/.m2/repository/lu/amazon/aws/demo/WebApp/1.0.0/WebApp-1.0.0.war ubuntu@172.31.90.45:/opt/tomcat/webapp/webapp.war
